[package]
name = "ipfis-modules-dummy-runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipfis-modules-dummy-api = { path = "../api" }
