[package]
name = "ipwis-modules-ipwis-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
avusen = { path = "../../../../avusen" }
ipwis-modules-ipwis-api = { path = "../api" }
